### ISSUE TITLE
RUN button is missing

### ISSUE THREAD

**Issue by araynard** [yskoht/keyboard-layouter#1]
Hello,
The run button is missing from the plugin window.
![image](https://user-images.githubusercontent.com/36554733/115140890-dc07a280-a039-11eb-8648-7e6b4c5b00f1.png)
I have prepared my json with the switch number at the top-left legend.

OS: Fedora 33 (Linux)
KiCAD: 5.1.9

**Comment by yskoht** [comment]
@araynard 

Thanks for the report!
I'll check it out.
