### ISSUE TITLE
Nothing happens after press run button

### ISSUE THREAD

**Issue by MondeCok** [yskoht/keyboard-layouter#3]
Hello,
after I press the run button nothing happens

OS : Windows 10
Kicad : 5.1.10

**Comment by MondeCok** [comment]
do i need special naming in schematic?

**Comment by yskoht** [comment]
@Sixtch 

Sorry, I didn't notice the issue.

In the Kayboard Layout Editor, you need to set the legend on the top left of the switch to a number.

And in KiCad, the reference name of the switch should be `SWx` (x is a number) and the reference name of the diode should be `Dx`.

<img width="1468" alt="SS_ 2021-10-25 17 26 08" src="https://user-images.githubusercontent.com/34795067/138661214-42e2235f-4acb-4c74-a3f5-81e5f86ae564.png">

A sample project is available at https://github.com/yskoht/keyboard-layouter-playground.

Please give it a try.

**Comment by riggtravis** [comment]
Do the switches need to start at 1? I'm trying to run starting from a 0 index and no switches are moving

**Comment by riggtravis** [comment]
After looking things over again I understood what you were saying. I'm going to create a PR this weekend to try to clarify the documentation presented in the README
